name: user_repository
description: Dart package which manages the user.
publish_to: 'none'
version: 0.1.0

#environment:
#  sdk: '>=3.1.0 <4.0.0'
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Firebase
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  post_repository:
    path: ../post_repository
  notification_repository:
    path: ../notification_repository

flutter:
  uses-material-design: true
