name: zinsta
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Services
  animated_flip_counter: ^0.3.4
  dart_jsonwebtoken: ^2.14.1
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
  get_it: ^8.0.0
  hugeicons: ^0.0.11
  image_cropper: ^9.0.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0

  # Local storages
  cached_network_image: ^3.4.0
  shared_preferences: ^2.2.3

  # Firebase
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5

  # Notifications
  onesignal_flutter: ^5.1.2

  # BLoCs
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  bloc_test: ^10.0.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0

  # GetStream
  stream_chat_flutter: ^9.10.0
  stream_chat_flutter_core: ^9.10.0
  stream_chat_localizations: ^9.10.0
  stream_chat_persistence: ^9.10.0
  stream_video: ^0.9.2
  stream_video_flutter: ^0.9.2
  stream_video_push_notification: ^0.9.2


  # Custom Repository
  user_repository:
    path: packages/user_repository
  post_repository:
    path: packages/post_repository
  notification_repository:
    path: packages/notification_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 19

flutter_native_splash:
  image: 'assets/icons/splash.png'
  color: "#FFFFFF"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/


  fonts:
    - family: IBM_Plex_Sans
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-Light.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSansArabic-Thin.ttf
    - family: SpecialGothicExpandedOne
      fonts:
        - asset: assets/fonts/SpecialGothicExpandedOne/SpecialGothicExpandedOne-Regular.ttf

flutter_intl:
  enabled: true