name: post_repository
description: Dart package which manages the posts.
publish_to: 'none'
version: 0.1.0

#environment:
#  sdk: '>=3.1.0 <4.0.0'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0

  # Firebase
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  # Custom Repository
  user_repository:
    path: ../user_repository
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
